# Generated by Django 3.2.1 on 2021-05-04 20:08

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
                ('detail', django.db.models.manager.Manager()),
            ],
        ),
    ]
