# Generated by Django 3.2.1 on 2021-05-04 20:28

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210504_2008'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='detail',
            managers=[
                ('deta', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
